create table if not exists quiz_questions (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('a','b','c','d')),
  explanation text,
  category text not null default 'afl' check (category in ('afl','wafl','general')),
  difficulty text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into quiz_questions (question, option_a, option_b, option_c, option_d, correct_option, explanation, category, difficulty) values
('How many players are on the field per team in AFL?', '16', '18', '20', '22', 'b', 'Each AFL team fields 18 players.', 'afl', 'easy'),
('What shape is an AFL football?', 'Round', 'Oval', 'Square', 'Hexagonal', 'b', 'AFL uses an oval-shaped ball.', 'afl', 'easy'),
('How many points is a goal worth in AFL?', '4', '6', '3', '5', 'b', 'A goal scores 6 points.', 'afl', 'easy'),
('How many points is a behind worth in AFL?', '1', '2', '3', '4', 'a', 'A behind scores 1 point.', 'afl', 'easy'),
('Which team is known as "The Magpies"?', 'Richmond', 'Collingwood', 'Carlton', 'Essendon', 'b', 'Collingwood are nicknamed The Magpies.', 'afl', 'easy'),
('Which team is known as "The Bombers"?', 'Hawthorn', 'West Coast', 'Essendon', 'Fremantle', 'c', 'Essendon are nicknamed The Bombers.', 'afl', 'easy'),
('In what year was the AFL (then VFL) founded?', '1877', '1897', '1920', '1960', 'a', 'The VFL was founded in 1877.', 'afl', 'easy'),
('Which club has won the most AFL/VFL premierships?', 'Collingwood', 'Carlton', 'Essendon', 'Hawthorn', 'b', 'Carlton has won 16 VFL/AFL premierships.', 'afl', 'medium'),
('What is the name of the AFL Grand Final venue?', 'Optus Stadium', 'MCG', 'Adelaide Oval', 'Gabba', 'b', 'The AFL Grand Final is traditionally held at the MCG.', 'afl', 'medium'),
('How long is each quarter in AFL?', '15 minutes', '20 minutes', 'Time-on applies, typically 25-30 minutes', '12 minutes', 'c', 'Quarters are 20 minutes plus time-on.', 'afl', 'medium'),
('What is the "Brownlow Medal" awarded for?', 'Best and fairest player', 'Leading goalkicker', 'Best young player', 'Grand Final MVP', 'a', 'The Brownlow Medal goes to the fairest and best player as voted by umpires.', 'afl', 'medium'),
('Which AFL club is nicknamed "The Hawks"?', 'West Coast', 'GWS Giants', 'Hawthorn', 'Gold Coast', 'c', 'Hawthorn are nicknamed The Hawks.', 'afl', 'medium'),
('What year did the Brisbane Lions last win a premiership?', '2002', '2003', '2009', '2011', 'b', 'Brisbane Lions won back-to-back-to-back from 2001-2003.', 'afl', 'medium'),
('What is the "Coleman Medal" awarded for?', 'Best ruckman', 'Leading goalkicker', 'Best first-year player', 'Best defender', 'b', 'The Coleman Medal goes to the AFL season leading goalkicker.', 'afl', 'medium'),
('Which team plays home games at Optus Stadium?', 'Fremantle only', 'West Coast only', 'Both Fremantle and West Coast', 'GWS Giants', 'c', 'Both Fremantle Dockers and West Coast Eagles share Optus Stadium.', 'afl', 'medium'),
('What does "HTB" stand for in AFL?', 'Hit The Ball', 'Holding The Ball', 'High To Back', 'Hand To Body', 'b', 'HTB is the Holding The Ball free kick rule.', 'afl', 'medium'),
('Which player has won the most Brownlow Medals?', 'Gary Ablett Jnr', 'Bob Skilton', 'Dick Reynolds', 'All equal on 3', 'd', 'Bob Skilton, Dick Reynolds, and Haydn Bunton each won 3 Brownlows.', 'afl', 'medium'),
('What is the record for most goals in an AFL/VFL game by one player?', '16', '17', '18', '20', 'c', 'Fred Fanning kicked 18 goals for Melbourne against St Kilda in 1947.', 'afl', 'hard'),
('Which year did South Melbourne relocate to become the Sydney Swans?', '1980', '1981', '1982', '1983', 'c', 'South Melbourne relocated to Sydney in 1982.', 'afl', 'hard'),
('What is the name of the trophy awarded to the AFL premiership winner?', 'The Cup', 'Premiership Cup', 'The Norm Smith Medal', 'The Flag', 'b', 'The winner receives the AFL Premiership Cup.', 'afl', 'hard'),
('Which AFL ground has the largest capacity?', 'MCG', 'Optus Stadium', 'Adelaide Oval', 'Marvel Stadium', 'a', 'The MCG has a capacity of approximately 100,024.', 'afl', 'hard'),
('In AFL, how many players can be on the interchange bench?', '3', '4', '5', '6', 'b', 'Teams can have 4 players on the interchange bench.', 'afl', 'hard'),
('Which team is the most successful in WAFL history by premierships?', 'East Fremantle', 'Subiaco', 'Claremont', 'South Fremantle', 'a', 'East Fremantle has won the most WAFL premierships.', 'wafl', 'medium'),
('What does WAFL stand for?', 'Western Australian Football League', 'West Australian Football League', 'Western AFL', 'WA Football League', 'b', 'WAFL stands for West Australian Football League.', 'wafl', 'easy'),
('Which WAFL club is nicknamed "The Lions"?', 'Subiaco', 'East Fremantle', 'Swan Districts', 'Perth', 'a', 'Subiaco are nicknamed The Lions.', 'wafl', 'easy'),
('At which ground do the WAFL Grand Finals traditionally take place?', 'Optus Stadium', 'Domain Stadium', 'Fremantle Oval', 'Medibank Stadium', 'a', 'WAFL Grand Finals are held at Optus Stadium.', 'wafl', 'medium'),
('Which WAFL club is based in the northern suburbs of Perth?', 'Swan Districts', 'Peel Thunder', 'Subiaco', 'Claremont', 'a', 'Swan Districts are based in the northern suburbs of Perth.', 'wafl', 'medium'),
('How many clubs currently compete in the WAFL?', '8', '9', '10', '12', 'c', 'There are 10 clubs in the WAFL.', 'wafl', 'easy'),
('Which individual award is considered the AFL equivalent of the Heisman Trophy?', 'Brownlow Medal', 'Norm Smith Medal', 'Coleman Medal', 'AFLPA MVP', 'a', 'The Brownlow Medal is the most prestigious individual award in AFL.', 'general', 'medium'),
('Which country hosted the first official international AFL Compromise Rules game?', 'USA', 'Ireland', 'UK', 'Canada', 'b', 'The first Compromise Rules game was played in Ireland.', 'general', 'hard');
